//! Build-time asset pipeline.
//!
//! Firmware has no PNG decoder and no allocator at the point we blit, so we
//! decode the SteamOS / Windows logos on the host (with the `image` crate),
//! downscale them to the size the UI draws them at, convert to **premultiplied
//! BGRA** (the Steam Deck GOP framebuffer is BGRA / BltOnly), and emit raw
//! `.bgra` blobs plus a generated `logos.rs` that `include_bytes!`-embeds them.
//!
//! Premultiplying here keeps the runtime alpha-compositing a single cheap
//! `src + dst*(1-a)` per channel — no division on the firmware side.

use std::{env, fs, path::Path};

/// Each logo is fit into a TARGET x TARGET box, preserving aspect ratio.
const TARGET: u32 = 200;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let logos = [
        ("steamos", "assets/src/steamos.png"),
        ("windows", "assets/src/windows.png"),
    ];

    let mut generated = String::from(
        "// @generated by build.rs — premultiplied BGRA logo blobs.\n\
         pub struct Logo { pub w: usize, pub h: usize, pub bgra: &'static [u8] }\n",
    );

    for (name, src) in logos {
        println!("cargo:rerun-if-changed={src}");
        let img = image::open(src)
            .unwrap_or_else(|e| panic!("decode {src}: {e}"))
            .into_rgba8();

        // Fit within TARGET box, preserving aspect ratio (Lanczos3 for clean edges).
        let (w0, h0) = img.dimensions();
        let scale = (TARGET as f32 / w0 as f32).min(TARGET as f32 / h0 as f32);
        let (w, h) = (((w0 as f32 * scale) as u32).max(1), ((h0 as f32 * scale) as u32).max(1));
        let scaled = image::imageops::resize(&img, w, h, image::imageops::FilterType::Lanczos3);

        // RGBA -> premultiplied BGRA.
        let mut bgra = Vec::with_capacity((w * h * 4) as usize);
        for px in scaled.pixels() {
            let [r, g, b, a] = px.0;
            let pm = |c: u8| ((c as u16 * a as u16) / 255) as u8;
            bgra.extend_from_slice(&[pm(b), pm(g), pm(r), a]);
        }

        let blob = Path::new(&out_dir).join(format!("{name}.bgra"));
        fs::write(&blob, &bgra).unwrap();
        generated.push_str(&format!(
            "pub static {}: Logo = Logo {{ w: {w}, h: {h}, \
             bgra: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}.bgra\")) }};\n",
            name.to_uppercase(),
        ));
    }

    fs::write(Path::new(&out_dir).join("logos.rs"), generated).unwrap();
}
